//-------------- ACTION
export const ACTION_GET_DATA_MARKETS_REQUEST="ACTION_GET_DATA_MARKETS_REQUEST";
export const ACTION_GET_DATA_MARKETS_SUCCESS="ACTION_GET_DATA_MARKETS_SUCCESS";
export const ACTION_GET_DATA_MARKETS_FAIL="ACTION_GET_DATA_MARKETS_FAIL";

//-------------- STATE
export const STATE_GET_DATA_MARKETS_IDLE="STATE_GET_DATA_MARKETS_IDLE";
export const STATE_GET_DATA_MARKETS_TRYING="STATE_GET_DATA_MARKETS_TRYING";
export const STATE_GET_DATA_MARKETS_SUCCESS="STATE_GET_DATA_MARKETS_SUCCESS";
export const STATE_GET_DATA_MARKETS_FAIL="STATE_GET_DATA_MARKETS_FAIL";